[tox]
min_version = 4.4.4
envlist =
    coverage-erase
    py{3.14, 3.13, 3.12, 3.11, 3.10}
    coverage-report
    coverage-html
    build{, -minimum}
    mypy
labels =
    update=update-{headers, pre_commit, requirements}


[testenv:coverage-erase]
description = Erase .coverage* files before testing
skip_install = true
deps =
    -rrequirements/test/requirements-coverage.txt
commands = coverage erase


[testenv:py{3.14, 3.13, 3.12, 3.11, 3.10}]
description = Run the test suite ({env_name})
depends =
    coverage-erase
package = wheel
wheel_build_env = build_wheel
deps =
    -rrequirements/test/requirements.txt
commands = {envpython} -W error -m coverage run -m pytest


[testenv:coverage-report]
description = Report code coverage after testing
depends =
    py{3.14, 3.13, 3.12, 3.11, 3.10}
skip_install = true
deps =
    -rrequirements/test/requirements-coverage.txt
commands_pre =
    -coverage combine
commands =
    coverage report


[testenv:coverage-html]
description = Generate an HTML coverage report
depends =
    coverage-report
skip_install = true
deps =
    -rrequirements/test/requirements-coverage.txt
commands =
    coverage html


[testenv:build{, -minimum}]
description =
    Test building the project
    minimum: (minimum requirements)
base_python =
    minimum: py3.10
skip_install = true
recreate = true
deps =
    build
    twine
    minimum: flit-core==3.12.0
    !minimum: flit-core<4
commands =
    python --version
    python -m build --outdir {envdir}/dist/ --no-isolation
    twine check --strict {envdir}/dist/*


[testenv:mypy]
description = Lint type annotations using mypy
deps =
    -rrequirements/mypy/requirements.txt
setenv =
    MYPY_FORCE_COLOR=1
commands = mypy


[testenv:update_base]
description = Base settings for update-* environments
base_python = py3.14
recreate = true
skip_install = true


[testenv:update-headers]
description = Update headers
base = update_base
deps =
    chipshot
commands =
    chipshot --update dotbot_firefox.py tests/ CHANGELOG.rst README.rst


[testenv:update-pre_commit]
description = Update pre-commit hooks
base = update_base
deps =
    prek
    upadup
commands =
    prek autoupdate --freeze
    upadup --freeze


[testenv:update-requirements]
description = Update requirements files
base = update_base
deps =
    poetry
    poetry-plugin-export
commands =
    poetry update --directory="requirements/mypy" --lock
    poetry export --directory="requirements/mypy" --output="requirements.txt" --without-hashes
    poetry update --directory="requirements/test" --lock
    poetry export --directory="requirements/test" --output="requirements.txt" --without-hashes
    poetry export --directory="requirements/test" --output="requirements-coverage.txt" --without-hashes --only="coverage"
