[tool.poetry]
name = "mypy requirements"
version = "0"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">=3.8"
mypy = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
